version: "3"

services:
  deadline_telegram_bot:
    container_name: deadline_telegram_bot
    image: deadline_telegram_bot:latest
    command: python3 deadline-telegram-bot/bot.py
    restart: always
    volumes:
      - ./config/config.yml:/code/config/config.yml
    environment:
      - "traefik.enable=false"